"""Created segmentation algorithm version

Revision ID: 37ed022c735c
Revises: 3c4561f828f7
Create Date: 2024-04-14 20:59:35.667840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '37ed022c735c'
down_revision: Union[str, None] = '3c4561f828f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segmentation_algorithm',
    sa.Column('released_datetime', sa.DateTime(), nullable=True),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('object_observation', sa.Column('segmentation_algorithm_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'object_observation', 'segmentation_algorithm', ['segmentation_algorithm_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'object_observation', type_='foreignkey')
    op.drop_column('object_observation', 'segmentation_algorithm_id')
    op.drop_table('segmentation_algorithm')
    # ### end Alembic commands ###
