"""Added unique constraint to object type names

Revision ID: 3c4561f828f7
Revises: f74290bfcf70
Create Date: 2024-04-14 20:38:00.844796

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "3c4561f828f7"
down_revision: Union[str, None] = "f74290bfcf70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("object_type", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.create_unique_constraint(None, "object_type", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "object_type", type_="unique")
    op.alter_column("object_type", "name", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
